### ISSUE TITLE
Segmentation fault during makeBloom

### ISSUE THREAD

**Issue by vmkalbskopf** [jengelmann/FastqPuri#6]
HI there

I am trying to make a Bloom filter.  I am running this interactively in the docker container.  The fasta file is 1.1 GB. 
Here is the command I used:

`makeBloom -f GCF_007115625.1_cibio_Scana_2019_genomic.fna -o bloom`

The first few lines of output are:

```
- Input file: GCF_007115625.1_cibio_Scana_2019_genomic.fna
- kmersize: 25
- Filter output file : bloom7m.bf
- Param output file : bloom7m.bf.txt
* STEP 1: Reading fasta file ...
 - Reading fasta file: GCF_007115625.1_cibio_Scana_2019_genomic.fna.
- Parameters:
- Allocating memory to store the contents of GCF_007115625.1_cibio_Scana_2019_genomic.fna.
- Current allocated memory: 1022MB.
 * Number of lines: 13400950
 * Number of entries: 3541
 * Length of lines: 80
 * Length of sequences in entries:  : [MANY LINES OF RANDOM LOOKING  DIGITS
```

The last 4 lines of the output is:

```
- Fasta file size: 1085652549bytes.
- Allocating 1085652549bytes in the buffer.
- Current allocated memory: 2057MB.
Segmentation fault (core dumped)
```

I'm at a loss to why this happened. I have enough RAM on this computer, at 32GB. 
Help?

**Comment by PaulaAlessio** [comment]
Hi, 
Indeed the fasta file is not being read properly. 

**Hotfix:** 
Change the variable `B_LEN` in `include/defines.h` to another value. Example given: 
```
define B_LEN 11131072  
```
recompile and create the filter again. It should work now. By running: 

```
makeBloom  -o mybloom -f GCF_007115625.1_cibio_Scana_2019_genomic.fna   -p 0.05 
```
I get:
```
bla bla bla ...
* STEP 5: Saving bloom filter to file ... 
Store a bloom filter in: mybloom.bf (filter), mybloom.bf.txt (param) 
Bloom filter size in bytes, 835317476
* STEP 6: Deallocating bloomfilter ... 
Finishing program at: Wed Jun 17 00:24:21 2020
Time elapsed: 348.897682 s.
```
We are working on the proper bugfix at the moment. A fixed version should be available at the end of the week. 

Two further remarks: 
1. One of the options `-p, -g, -m` has to be given when creating a bloom filter (see [README](https://github.com/jengelmann/FastqPuri/blob/master/README_makeBloom.md)).
2. The "RANDOM DIGITS" will be also corrected in the next version. This list is supposed to give the length of each entry, but a blank character is just missing between entries.

**Comment by vmkalbskopf** [comment]
The reason I am running this using docker is that I am getting make errors when I try to compile it. I realise that is another issue though. Is there another way to apply this hotfix?
EDIT: I will wait for you to release the fixed version and then I'll rebuild the docker ;-)

**Comment by PaulaAlessio** [comment]
Hi, can you try now to install it? I have just pushed the bugfix. 
I have run  
```
makeBloom  -o bloom -f GCF_007115625.1_cibio_Scana_2019_genomic.fna   -p 0.05 
```
and the `bloom.bf.txt` file looks like:
```
kmersize = 25
hashNum = 4
bfsizeBits = 6682539808
falsePosRate = 0.050000
nelem = 1071740095
```
Does it look the same for you? 

PS: Can you describe your compilation issues?

**Comment by vmkalbskopf** [comment]
Is this fix part of a release? Or shall I git clone this repo again?

I'll post about the compilation problem in a new issue if it happens again with the new version.

**Comment by clottaz** [comment]
The fix is not yet part of a release and I did not yet have the time to update our docker image. You can try to pull the fix in your local repository and generate your own docker image as shown in README.md under "Use a docker container to run FastqPuri".

**Comment by vmkalbskopf** [comment]
I created a separate issue for the compiling issue.

I rebuilt the docker container from a fresh pull from this repo.  Now `makeBloom`  gave me a different error. 

`makeBloom -f PlasmoDB-39_PrelictumSGS1-like_Genome.fasta -o prelictum_bloom`

```
...
[random digits]
- Fasta file size: 23046930bytes. 
- Allocating 23046930bytes in the buffer. 
- Current allocated memory: 43MB.
- Deallocating the buffer.
- Contents of PlasmoDB-39_PrelictumSGS1-like_Genome.fasta allocated.
- Current allocated memory: 21MB.
* STEP 2: Setting parameters for the filter ... 
* STEP 3: Constructing bloomfilter ... 
Allocating 2305843009194750839 bytes of memory to 0.
Error when allocating memory for the bloom filter.
Exiting program.
File: /home/FastqPuri/src/bloom.c, line: 133
```

**Comment by PaulaAlessio** [comment]
Have you passed the option `-p 0.05`? You must pass either -p, -g, -m, as described in the [README](https://github.com/jengelmann/FastqPuri/blob/master/README_makeBloom.md) file. Maybe it should be better described...

**Comment by vmkalbskopf** [comment]
It's not marked as mandatory, and -p has a default value, so I didn't think that was necessary. I'll check it tomorrow.

` -p, --fal_pos_rate false positive rate. Optional (default = 0.05)`

**Comment by PaulaAlessio** [comment]
Indeed... I'll look into that.

**Comment by PaulaAlessio** [comment]
You should be able to call the program without the -p option now.

**Comment by vmkalbskopf** [comment]
Yes I can! Thank you! I'm really impressed with your quick responses and fixes.
