### ISSUE TITLE
genome.bf.txt not found and needed to create the Bfilter

### ISSUE THREAD

**Issue by vmkalbskopf** [jengelmann/FastqPuri#8]
I am trying to remove contaminating reads using `trimFilterPE`.
I created the bloom filter file using `makeBloom`. It is called `genome.bf`. When I try to run `trimFilterPE` however, I get this error:

` trimFilterPE -f R52.1.fq.gz:R52.2.fq.gz -l 150 -o ./fastqpuri --method BLOOM --idx genome.bf:0.005`

```
trimFilterPE from FastqPuri
f
l
o
C
x
- Fastq input file1: R52.1.fq.gz 
- Fastq input file2: R52.2.fq.gz 
- Read length: 150.
- Output prefix: ./fastqpuri.
- Output files will be compressed.
- Not looking for adapter sequences.
- Min Quality: 27 (default value).
- Zero quality ASCII character: Phred+33 (default value)
- Looking for contaminations with a bloom filter.
- Reading Bloom filter from file scanaria_0-005_bloom.bf.
- Threshold score: 0.005000
- Trimming low Q bases method: NO
- Trimming reads with N's, method: NO
- Minimum accepted trimmed read length: 25 (default).
Starting trimFilterPE at: Fri Jun 19 13:11:03 2020
gzip: Success
gzip: Success
File genome.bf.txt not found and needed to create the Bfilter.
Exiting program.
File: /home/vmkalbskopf/bin/FastqPuri/src/bloom.c, line: 593
```
Where does the txt come from? Am I missing something obvious?

I tried renaming `genome.bf` to `genome.bf.txt` and then the error was:
`File genome.bf.txt.txt not found and needed to create the Bfilter.`

**Comment by PaulaAlessio** [comment]
When the bloom filter is generated, it should also generate a file named `genome.bf.txt` along with `<mybloomfiltername>.bf`. Does it do it for you?

**Comment by vmkalbskopf** [comment]
Sigh.. I copied the .bf file to pwd, but not the .bf.txt file because I didn't realise it was necessary. I'm feeling rather silly now. Thanks for your help.
